name: Deploy to EC2

on:
  push:
    branches:
      - main # Despliega solo cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: deploy Apache
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 98.81.97.10
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /Action/
            sudo git pull https://github.com/dcaguilarc/aguilarec2.git
            sudo systemctl restart httpd
          debug: true